import { MetricType } from "@/components/Editor";
import { UserLove01Icon, CheckmarkBadge02Icon, UserAdd01Icon, UserAdd02Icon, News01Icon, EyeIcon, Comment01Icon, Activity01Icon, Tap01Icon, UserCircleIcon, FavouriteIcon, RepeatIcon, Bookmark01Icon, DollarCircleIcon, DollarReceive01Icon, ChartLineData01Icon, ChartIncreaseIcon, SaleTag01Icon, ChartDecreaseIcon, MoneyBag01Icon, UserGroupIcon, DashboardSpeed01Icon, StarIcon, GitCommitIcon, GitForkIcon, UserMultipleIcon, GitPullRequestClosedIcon, CheckmarkCircle01Icon, UploadSquare01Icon, ThumbsUpIcon, ThumbsUpDownIcon, AccountSetting03Icon, Globe02Icon, Tag01Icon } from "@hugeicons/core-free-icons";
import { IconSvgElement } from "@hugeicons/react";

export const METRIC_ICONS: Record<MetricType, IconSvgElement> = {
  followers: UserLove01Icon,
  verifiedFollowers: CheckmarkBadge02Icon,
  followings: UserAdd01Icon,
  posts: News01Icon,
  impressions: EyeIcon,
  replies: Comment01Icon,
  engagementRate: Activity01Icon,
  engagement: Tap01Icon,
  profileVisits: UserCircleIcon,
  likes: FavouriteIcon,
  reposts: RepeatIcon,
  bookmarks: Bookmark01Icon,
  builders: AccountSetting03Icon,
  mrr: DollarCircleIcon,
  arr: ChartLineData01Icon,
  valuation: ChartIncreaseIcon,
  revenue: MoneyBag01Icon,
  churnRate: ChartDecreaseIcon,
  ltv: DollarReceive01Icon,
  newCustomers: UserAdd02Icon,
  totalCustomers: UserGroupIcon,
  sales: SaleTag01Icon,
  visitors: Globe02Icon,
  domainRating: DashboardSpeed01Icon,
  githubStars: StarIcon,
  githubCommits: GitCommitIcon,
  githubForks: GitForkIcon,
  githubContributors: UserMultipleIcon,
  githubPRsClosed: GitPullRequestClosedIcon,
  githubIssuesResolved: CheckmarkCircle01Icon,
  redditKarma: UploadSquare01Icon,
  redditUpvotes: ThumbsUpIcon,
  redditUpvoteRatio: ThumbsUpDownIcon,
  custom: Tag01Icon,
};
